version: "3.8"

services:
  web:
    build: .
    ports: 
      - "5000:5000"
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret  
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
